//! Differential test against Go's `regexp` (the golden reference).
//!
//! `cases.jsonl` is generated by a Go program that runs
//! `regexp.Compile` + `FindStringSubmatchIndex` over a large corpus of
//! (pattern, input) pairs; each line is `{p, i, err, m}`. This test recompiles
//! every pattern with our engine and checks that the submatch-index result is
//! byte-for-byte identical. `std.testing.allocator` additionally proves the
//! engine leaks no memory across all cases.
//!
//! Run on its own:  zig test src/difftest.zig

const std = @import("std");
const regex = @import("regexp.zig");

const Case = struct {
    p: []const u8,
    i: []const u8,
    err: bool,
    m: ?[]i64,
};

const data = @embedFile("cases.jsonl");

test "differential vs Go regexp" {
    const gpa = std.testing.allocator;
    var total: usize = 0;
    var passed: usize = 0;
    var mismatches: usize = 0;
    var shown: usize = 0;

    var it = std.mem.tokenizeScalar(u8, data, '\n');
    while (it.next()) |line| {
        if (line.len == 0) continue;
        total += 1;

        const parsed = try std.json.parseFromSlice(Case, gpa, line, .{});
        defer parsed.deinit();
        const c = parsed.value;

        const ok = checkCase(gpa, c) catch |e| {
            mismatches += 1;
            if (shown < 30) {
                shown += 1;
                std.debug.print("EXEC-ERR {s} on /{s}/ \"{s}\"\n", .{ @errorName(e), c.p, c.i });
            }
            continue;
        };
        if (ok) {
            passed += 1;
        } else {
            mismatches += 1;
            if (shown < 30) {
                shown += 1;
                reportMismatch(gpa, c);
            }
        }
    }

    std.debug.print("\n[differential] total={d} passed={d} mismatches={d}\n", .{ total, passed, mismatches });
    try std.testing.expectEqual(@as(usize, 0), mismatches);
}

fn checkCase(gpa: std.mem.Allocator, c: Case) !bool {
    var re = regex.compile(gpa, c.p) catch {
        return c.err; // we errored; correct iff Go also errored
    };
    defer re.deinit();
    if (c.err) return false; // Go errored, we did not

    const got = try re.findSubmatchIndex(gpa, c.i);
    defer if (got) |g| gpa.free(g);

    if (c.m == null) return got == null;
    if (got == null) return false;
    const want = c.m.?;
    const g = got.?;
    if (want.len != g.len) return false;
    for (want, g) |a, b| {
        if (a != b) return false;
    }
    return true;
}

fn reportMismatch(gpa: std.mem.Allocator, c: Case) void {
    std.debug.print("MISMATCH /{s}/ \"{s}\"\n   go : err={} m={?any}\n", .{ c.p, c.i, c.err, c.m });
    var re = regex.compile(gpa, c.p) catch {
        std.debug.print("   zig: <compile error>\n", .{});
        return;
    };
    defer re.deinit();
    const got = re.findSubmatchIndex(gpa, c.i) catch {
        std.debug.print("   zig: <exec error>\n", .{});
        return;
    };
    defer if (got) |g| gpa.free(g);
    std.debug.print("   zig: m={?any}\n", .{got});
}
