//! Large randomized differential test against Go's `regexp`.
//!
//! `fuzz.jsonl` is generated by a grammar-driven random regex generator in Go
//! (kept within this engine's supported feature set). For each (pattern, input)
//! Go records FindStringSubmatchIndex (`m`), FindAllStringSubmatchIndex (`all`),
//! ReplaceAllString with template "[$0/$1]" (`repl`), and Split (`split`). This
//! test checks our engine reproduces all four, exactly.
//!
//! Run on its own:  zig test src/fuzztest.zig

const std = @import("std");
const regex = @import("regexp.zig");
const common = @import("difftest_common.zig");
const eqOptInts = common.eqOptInts;
const eqOptNested = common.eqOptNested;

const repl_template = "[$0/$1]";

const Case = struct {
    p: []const u8,
    i: []const u8,
    err: bool,
    m: ?[]i64,
    all: ?[][]i64,
    repl: []const u8,
    split: ?[][]const u8,
};

const data = @embedFile("fuzz.jsonl");

test "fuzz differential vs Go regexp" {
    const gpa = std.testing.allocator;
    var total: usize = 0;
    var passed: usize = 0;
    var fails = [_]usize{0} ** 5; // m, all, repl, split, compile
    var shown: usize = 0;

    var it = std.mem.tokenizeScalar(u8, data, '\n');
    while (it.next()) |line| {
        if (line.len == 0) continue;
        total += 1;
        const parsed = try std.json.parseFromSlice(Case, gpa, line, .{});
        defer parsed.deinit();
        const c = parsed.value;

        var re = regex.compile(gpa, c.p) catch {
            if (!c.err) {
                fails[4] += 1;
                if (shown < 25) {
                    shown += 1;
                    std.debug.print("COMPILE-FAIL (Go ok) /{s}/\n", .{c.p});
                }
            }
            continue;
        };
        defer re.deinit();
        if (c.err) {
            fails[4] += 1;
            continue;
        }

        const which = try checkAll(gpa, &re, c);
        if (which == 0) {
            passed += 1;
        } else {
            fails[which - 1] += 1;
            if (shown < 25) {
                shown += 1;
                std.debug.print("MISMATCH[{s}] /{s}/ \"{s}\"\n", .{ kindName(which), c.p, c.i });
            }
        }
    }

    std.debug.print("\n[fuzz] total={d} passed={d} m_fail={d} all_fail={d} repl_fail={d} split_fail={d} compile_fail={d}\n", .{ total, passed, fails[0], fails[1], fails[2], fails[3], fails[4] });
    for (fails) |f| try std.testing.expectEqual(@as(usize, 0), f);
}

fn kindName(w: usize) []const u8 {
    return switch (w) {
        1 => "m",
        2 => "all",
        3 => "repl",
        4 => "split",
        else => "compile",
    };
}

/// Returns 0 on full match, else the 1-based index of the first failing check.
fn checkAll(gpa: std.mem.Allocator, re: *regex.Regexp, c: Case) !usize {
    // 1: findSubmatchIndex
    {
        const got = try re.findSubmatchIndex(gpa, c.i);
        defer if (got) |g| gpa.free(g);
        if (!eqOptInts(c.m, got)) return 1;
    }
    // 2: findAllSubmatchIndex
    {
        const got = try re.findAllSubmatchIndex(gpa, c.i, -1);
        defer if (got) |g| regex.Regexp.freeAllSubmatchIndex(gpa, g);
        if (!eqOptNested(c.all, got)) return 2;
    }
    // 3: replaceAllString
    {
        const got = try re.replaceAllString(gpa, c.i, repl_template);
        defer gpa.free(got);
        if (!std.mem.eql(u8, c.repl, got)) return 3;
    }
    // 4: split
    {
        const got = (try re.split(gpa, c.i, -1)).?;
        defer gpa.free(got);
        const want = c.split orelse &[_][]const u8{};
        if (want.len != got.len) return 4;
        for (want, got) |a, b| {
            if (!std.mem.eql(u8, a, b)) return 4;
        }
    }
    return 0;
}
