//! Differential test for POSIX leftmost-longest mode.
//!
//! `longest.jsonl` is generated by compiling Perl-syntax patterns in Go and
//! then calling `Regexp.Longest()` (isolating the leftmost-longest *semantics*
//! from POSIX *syntax*). This checks our `setLongest()` path — the `longest`
//! branches in the Pike VM's step/match loop — matches Go exactly.
//!
//! Run on its own:  zig test src/longesttest.zig

const std = @import("std");
const regex = @import("regexp.zig");
const common = @import("difftest_common.zig");
const eqOptInts = common.eqOptInts;
const eqOptNested = common.eqOptNested;

const LCase = struct {
    p: []const u8,
    i: []const u8,
    m: ?[]i64,
    all: ?[][]i64,
};

const data = @embedFile("longest.jsonl");

test "leftmost-longest differential vs Go" {
    const gpa = std.testing.allocator;
    var total: usize = 0;
    var passed: usize = 0;
    var m_fail: usize = 0;
    var all_fail: usize = 0;
    var shown: usize = 0;

    var it = std.mem.tokenizeScalar(u8, data, '\n');
    while (it.next()) |line| {
        if (line.len == 0) continue;
        total += 1;
        const parsed = try std.json.parseFromSlice(LCase, gpa, line, .{});
        defer parsed.deinit();
        const c = parsed.value;

        var re = try regex.compile(gpa, c.p);
        re.setLongest();
        defer re.deinit();

        var ok = true;
        {
            const got = try re.findSubmatchIndex(gpa, c.i);
            defer if (got) |g| gpa.free(g);
            if (!eqOptInts(c.m, got)) {
                ok = false;
                m_fail += 1;
                if (shown < 20) {
                    shown += 1;
                    std.debug.print("M /{s}/ \"{s}\" go={?any} zig={?any}\n", .{ c.p, c.i, c.m, got });
                }
            }
        }
        if (ok) {
            const got = try re.findAllSubmatchIndex(gpa, c.i, -1);
            defer if (got) |g| regex.Regexp.freeAllSubmatchIndex(gpa, g);
            if (!eqOptNested(c.all, got)) {
                ok = false;
                all_fail += 1;
                if (shown < 20) {
                    shown += 1;
                    std.debug.print("ALL /{s}/ \"{s}\"\n", .{ c.p, c.i });
                }
            }
        }
        if (ok) passed += 1;
    }

    std.debug.print("\n[longest] total={d} passed={d} m_fail={d} all_fail={d}\n", .{ total, passed, m_fail, all_fail });
    try std.testing.expectEqual(@as(usize, 0), m_fail + all_fail);
}
